/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BreadHeader: typeof import('./src/components/layout/BreadHeader.vue')['default']
    ContentFooter: typeof import('./src/components/layout/ContentFooter.vue')['default']
    Frame: typeof import('./src/components/layout/Frame.vue')['default']
    GlobalSetting: typeof import('./src/components/core/GlobalSetting.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    Menu: typeof import('./src/components/layout/Menu.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NColors: typeof import('./src/components/core/NColors.vue')['default']
    NImage: typeof import('naive-ui')['NImage']
    NLayout: typeof import('naive-ui')['NLayout']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
